//-----------------------------------------------------------------------
// 此文件由TryCostEngine自动生成
// 对该文件的任何更改都将在生成时被覆盖
// <auto-generated />
//-----------------------------------------------------------------------

namespace TryCostEngine.MAUI.Models
{
    public static partial class DocStrings
    {
        public const string BasicInfo = @"立项信息";

        public const string BasicInfo_TerminalName = @"终端名称";

        public const string BasicInfo_StartDay = @"协议开始日期";

        public const string BasicInfo_EndDay = @"协议截止日期";

        public const string BasicInfo_ContractMonths = @"合同月份";

        public const string BasicInfo_Agent1st = @"一批商";

        public const string BasicInfo_Agent2nd = @"二批商";

        public const string BasicInfo_CompanyFeeRate = @"公司承担比例";

        public const string BasicInfo_Agent1stFeeRate = @"一批商承担比例";

        public const string BasicInfo_Agent2ndFeeRate = @"二批商承担比例";

        public const string Beer = @"产品名称、价格、及比例";

        public const string Beer_id = @"";

        public const string Beer_name = @"";

        public const string Beer_price = @"";

        public const string Beer_packageRate = @"";

        public const string CloneExtends = @"";

        public const string CloneExtends_method_T_DeepCloneObject_T__T_ = @"
            <summary>
            深度克隆一个对象
            </summary>
            <typeparam name=""T""></typeparam>
            <param name=""t""></param>
            <returns></returns>
        ";

        public const string CloneExtends_method_System_Collections_Generic_IList_1_T__DeepCloneList_T__System_Collections_Generic_IList_1_T__ = @"
            <summary>
            深度克隆一个集合
            </summary>
            <typeparam name=""T""></typeparam>
            <param name=""tList""></param>
            <returns></returns>
        ";

        public const string CloneExtends_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal__CloneDictionary_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal__ = @"
            <summary>
            克隆一个字典
            </summary>
            <param name=""p""></param>
            <returns></returns>
        ";

        public const string CloneExtends_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___CloneArrayDictionary_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"
            <summary>
            克隆一个数组字典
            </summary>
            <param name=""p""></param>
            <returns></returns>
        ";

        public const string Config = @"";

        public const string Config_DateFormat = @"日期格式";

        public const string Config_DateTimeFormat = @"日期时间格式";

        public const string Config_DateTimeFormatS = @"日期时间格式(带秒)";

        public const string CostEntry = @"";

        public const string CostEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string CostEntry_method_System_String_calcCost__ = @"";

        public const string CostEntry_method_System_Collections_Generic_List_1_CostEngine_CostResults__getJsonResults__ = @"";

        public const string CostEntry___c = @"";

        public const string CostResults = @"";

        public const string CostResults_CostType = @"";

        public const string CostResults_PromotionID = @"";

        public const string CostResults_ProductID = @"";

        public const string CostResults_ProductName = @"";

        public const string CostResults_CostbyMonth = @"";

        public const string DataTableUtility = @"DataTable扩展类";

        public const string DataTableUtility_method_System_Data_DataTable_ToDataTable_T__System_Collections_Generic_IEnumerable_1_T__ = @"
            <summary>    
            转化一个DataTable    
            </summary>    
            <typeparam name=""T""></typeparam>    
            <param name=""list""></param>    
            <returns></returns>    
        ";

        public const string DataTableUtility_method_System_Data_DataTable_ToDataTableChineseColumn_T__System_Collections_Generic_IEnumerable_1_T__ = @"
            <summary>    
            转化一个DataTable 中文列，Model必须有DisplayName属性   
            </summary>    
            <typeparam name=""T""></typeparam>    
            <param name=""list""></param>    
            <returns></returns>    
        ";

        public const string DataTableUtility_method_System_Collections_Generic_List_1_T__ToList_T__System_Data_DataTable_ = @"
            <summary>    
            DataTable 转换为List 集合    
            </summary>    
            <typeparam name=""TResult"">类型</typeparam>    
            <param name=""dt"">DataTable</param>    
            <returns></returns>    
        ";

        public const string DataTableUtility_method_System_Data_DataTable_ToDataTableTow_System_Collections_IList_ = @"
            <summary>    
            将集合类转换成DataTable    
            </summary>    
            <param name=""list"">集合</param>    
            <returns></returns>    
        ";

        public const string DataTableUtility_method_System_Data_DataTable_ToDataTable_T__System_Collections_Generic_IList_1_T__ = @"
            <summary>    
            将泛型集合类转换成DataTable    
            </summary>    
            <typeparam name=""T"">集合项类型</typeparam>    
            <param name=""list"">集合</param>    
            <returns>数据集(表)</returns>    
        ";

        public const string DataTableUtility_method_System_Data_DataTable_ToDataTable_T__System_Collections_Generic_IList_1_T___System_String___ = @"
            <summary>    
            将泛型集合类转换成DataTable    
            </summary>    
            <typeparam name=""T"">集合项类型</typeparam>    
            <param name=""list"">集合</param>    
            <param name=""propertyName"">需要返回的列的列名</param>    
            <returns>数据集(表)</returns>    
        ";

        public const string DataTableUtility_method_System_Data_DataTable_ListToTable_T__System_Collections_Generic_List_1_T___Boolean_ = @"
            <summary>
            把List转换成Datatable
            </summary>
            <typeparam name=""T""></typeparam>
            <param name=""list""></param>
            <param name=""isStoreDB""></param>
            <returns></returns>
        ";

        public const string DataTableUtility___c__DisplayClass0_0 = @"";

        public const string DataTableUtility___c__DisplayClass0_1 = @"";

        public const string DataTableUtility___c__DisplayClass1_0 = @"";

        public const string DataTableUtility___c__DisplayClass1_1 = @"";

        public const string DataTableUtility___c__DisplayClass2_0 = @"";

        public const string DataTableUtility___c__DisplayClass2_1 = @"";

        public const string ET_ConfigCalcData = @"";

        public const string ET_ConfigCalcData_GongTanFee = @"";

        public const string ET_ConfigCalcData_FixedFee = @"";

        public const string ET_ConfigCostTax = @"";

        public const string ET_ConfigCostTax_CostChanged = @"";

        public const string ET_ConfigCostTax_SaleTax = @"";

        public const string ET_ConfigCostTax_BuildingTax = @"";

        public const string ET_ConfigCostTax_AdditionalTax = @"";

        public const string ET_ConfigPriceSet = @"";

        public const string ET_ConfigPriceSet_ShowNm = @"";

        public const string ET_ConfigPriceSet_Sort = @"";

        public const string ET_ConfigPriceSet_ColumnNm = @"";

        public const string ET_ConfigTaxRatio = @"";

        public const string ET_ConfigTaxRatio_TaxRatioType = @"";

        public const string ET_ConfigTaxRatio_TaxRatio = @"";

        public const string ET_D_PriceSysSet = @"价格因子配置";

        public const string ET_D_PriceSysSet_RegionCD = @"";

        public const string ET_D_PriceSysSet_Version = @"";

        public const string ET_D_PriceSysSet_FieldNm = @"列名";

        public const string ET_D_PriceSysSet_BusinessItemL2 = @"业务事项二级";

        public const string ET_D_PriceSysSet_MeasureRate = @"比例";

        public const string ET_M_PriceSys = @"";

        public const string ET_M_PriceSys_result = @"";

        public const string ET_M_PriceSys_Cur1 = @"";

        public const string ET_M_PriceSys_Cur2 = @"";

        public const string ET_M_PriceSys_Cur3 = @"";

        public const string ET_M_PriceSys_Cur4 = @"";

        public const string ET_M_PriceSys_Cur5 = @"";

        public const string ET_M_PriceSys_Cur6 = @"";

        public const string ET_M_PriceSys_Cur7 = @"";

        public const string ET_M_PriceSys_Cur8 = @"";

        public const string ET_M_PriceSys_Cur9 = @"";

        public const string ET_M_PriceSys_Field1 = @"";

        public const string ET_M_PriceSys_Field2 = @"";

        public const string ET_M_PriceSys_Field3 = @"";

        public const string ET_M_PriceSys_Field4 = @"";

        public const string ET_M_PriceSys_Field5 = @"";

        public const string ET_M_PriceSys_Field6 = @"";

        public const string ET_M_PriceSys_Field7 = @"";

        public const string ET_M_PriceSys_Field8 = @"";

        public const string ET_M_PriceSys_Field9 = @"";

        public const string ET_M_PriceSys_Field10 = @"";

        public const string ET_M_PriceSys_Field11 = @"";

        public const string ET_M_PriceSys_Field12 = @"";

        public const string ET_ProfitCalculateSysSet = @"";

        public const string ET_ProfitCalculateSysSet_FieldNo = @"";

        public const string ET_ProfitCalculateSysSet_FieldNm = @"";

        public const string ET_ProfitCalculateSysSet_FieldDesc = @"";

        public const string ET_ProfitCalculateSysSet_ColumnNm = @"";

        public const string ET_SP_P_IMDelayedDiscount = @"延后折";

        public const string ET_SP_P_IMDelayedDiscount_MarketOrg = @"";

        public const string ET_SP_P_IMDelayedDiscount_BigAreaOrg = @"";

        public const string ET_SP_P_IMDelayedDiscount_OfficeOrg = @"";

        public const string ET_SP_P_IMDelayedDiscount_StationOrg = @"";

        public const string ET_SP_P_IMDelayedDiscount_DTCD = @"";

        public const string ET_SP_P_IMDelayedDiscount_UnitRatio = @"";

        public const string ET_SP_P_IMDelayedDiscount_Level2CD = @"";

        public const string ET_SP_P_IMDelayedDiscount_ProductCD = @"";

        public const string ET_SP_P_IMDelayedDiscount_CharacterCD = @"";

        public const string ET_SP_P_IMDelayedDiscount_OverTime = @"";

        public const string ET_SP_P_IMDelayedDiscount_DateStart = @"";

        public const string ET_SP_P_IMDelayedDiscount_DateEnd = @"";

        public const string ExpressionCalc = @"数学公式计算类";

        public const string ExpressionCalc_method_Double_CalcMath_System_String_ = @"";

        public const string FormulaCalc = @"";

        public const string FormulaCalc_method_System_String_CalcMath_System_String__System_String__System_String__System_String__System_String__System_String__System_String__System_String__System_String__System_Collections_Generic_Dictionary_2_System_String_System_Decimal__ = @"";

        public const string FormulaCalc_method_System_String_GetValue_System_String__System_String__System_String__System_String__System_String__System_String__System_String__System_String__System_String____System_Collections_Generic_Dictionary_2_System_String_System_Decimal__ = @"";

        public const string FormulaCalc_method_System_String_GetBreakEvenPoint_System_Collections_Generic_Dictionary_2_System_String_System_Decimal___System_Collections_Generic_Dictionary_2_System_String_System_Decimal___System_Collections_Generic_List_1_System_String___System_String_ = @"";

        public const string FormulaCalc_method_System_String_CombinationQueryforMPricesys_System_String__System_String__System_String__System_String__System_String__System_String__System_String_ = @"";

        public const string FormulaCalc___c = @"";

        public const string FormulaCalc___c__DisplayClass14_0 = @"";

        public const string GetformulaValue = @"利润测算公式";

        public const string GetformulaValue_result = @"";

        public const string GiftBeer = @"";

        public const string GiftBeer_productID = @"";

        public const string GiftBeer_productName = @"";

        public const string GiftBeer_baseNum = @"";

        public const string GiftBeer_giftNum = @"";

        public const string GiftBeer_giftNumCompany = @"";

        public const string GiftBeer_price = @"";

        public const string GiftThing = @"";

        public const string GiftThing_productID = @"";

        public const string GiftThing_giftName = @"";

        public const string GiftThing_baseNum = @"";

        public const string GiftThing_giftNum = @"";

        public const string GiftThing_giftNumCompany = @"";

        public const string GiftThing_price = @"";

        public const string GiftThing_companyType = @"";

        public const string IndexColumn = @"索引列";

        public const string IndexColumn_FiledName = @"";

        public const string IndexColumn_sort = @"";

        public const string IndexData = @"索引数据";

        public const string IndexData_IndexTable = @"索引数据表";

        public const string IndexData_IndexName = @"索引名称";

        public const string IndexData_IndexAliaName = @"索引别名";

        public const string IndexData_CreatedIndexTime = @"索索创建时间";

        public const string IndexData_IndexUsedCounts = @"索引使用次数";

        public const string IndexData_IndexLastUserTime = @"索引最后一次使用时间";

        public const string IndexData_filter = @"条件";

        public const string IndexData_IndexColumns = @"索引列";

        public const string IndexData_DataTable = @"获取DataTable";

        public const string IndexData_method_Boolean_AddData_T_ = @"
            <summary>
            添加数据
            </summary>
            <param name=""data""></param>
            <returns></returns>
        ";

        public const string IndexData_____c = @"";

        public const string LightList = @"轻量级内存List对象（用以支持二分查找）
            使用须知(重要):
            (1)任何一张索引表中的字段内容改变，所有索引表将中将同步改变
            (2)排序字段值改变不会重新排序，凡是用此字段排序的索引表，进行二分查找时可能得不到完整的数据，不要对排序字段进行修改
            (3)使用BinarySearchRows时应遵循排序列的顺序，如对a,b,c排序，应使用BinarySearchRows(a) 或 BinarySearchRows(a).BinarySearchRows(b) 或 BinarySearchRows(a).BinarySearchRows(b).BinarySearchRows(c)
            (4)小数据量情况下不建议使用
            (5)只支持升序排序
            (6)多线程环境下，如果同时进行查询和添加操作，会导致查询的数据不正确，使用者应自行处理并发环境下的线程安全";

        public const string LightList_PrimaryIndex = @"主键索引";

        public const string LightList_KeyColumns = @"主键列";

        public const string LightList_TableName = @"表名";

        public const string LightList_DataTableDefaultView = @"数据视图";

        public const string LightList_IndexSetfaultView = @"索引集合视图";

        public const string LightList_method_Void_CreatedPrimaryIndex_CostEngine_Util_IndexColumn___ = @"
            <summary>
            创建主键索引，每次调用将进行主键索引重建,主键列只能是一般数据类型
            </summary>
            <param name=""keyColumns"">主键要求唯一</param>
        ";

        public const string LightList_method_T_Find_System_String_ = @"
            <summary>
            根据主键获取数据
            </summary>
            <returns></returns>
        ";

        public const string LightList_method_Void_CreateIndex_System_String__System_Collections_Generic_List_1_CostEngine_Util_IndexColumn__ = @"
            <summary>
            创建索引
            </summary>
            <param name=""indexName"">索引名</param>
            <param name=""indexColumns"">索引列</param>
        ";

        public const string LightList_method_Void_CreateIndex_System_String__System_Collections_Generic_List_1_CostEngine_Util_IndexColumn___System_Linq_Expressions_Expression_1_System_Func_2_T_System_Boolean___ = @"
            <summary>
            创建索引
            </summary>
            <param name=""indexName"">索引名</param>
            <param name=""indexColumns"">索引列</param>
            <param name=""expression"">条件</param>
        ";

        public const string LightList_method_Void_CreateIndex_System_String__CostEngine_Util_IndexColumn____System_Linq_Expressions_Expression_1_System_Func_2_T_System_Boolean___ = @"
            <summary>
            创建索引
            </summary>
            <param name=""indexName"">索引名</param>
            <param name=""indexColumns"">索引列</param>
            <param name=""expression"">条件</param>
        ";

        public const string LightList_method_Void_CreateIndex_System_String__CostEngine_Util_IndexColumn___ = @"
            <summary>
            创建索引
            </summary>
            <param name=""indexName""></param>
            <param name=""indexColumns""></param>
        ";

        public const string LightList_method_System_Collections_Generic_List_1_T__GetDataByIndexName_System_String_ = @"
            <summary>
            根据索引名获取索引数据对象
            </summary>
            <param name=""indexName""></param>
            <returns></returns>
        ";

        public const string LightList_method_Void_DropIndex_System_String_ = @"
            <summary>
            删除指定的索引数据对象
            </summary>
            <param name=""indexName""></param>
        ";

        public const string LightList_method_Void_AddData_T_ = @"
            <summary>
            添加数据,自动更新所有数据
            </summary>
            <param name=""data""></param>
        ";

        public const string LightList_____c = @"";

        public const string LightList_____c__DisplayClass24_0 = @"";

        public const string LightList_____c__DisplayClass25_0 = @"";

        public const string LightList_____c__DisplayClass28_0 = @"";

        public const string LightList_____c__DisplayClass29_0 = @"";

        public const string LightList_____c__DisplayClass30_0 = @"";

        public const string ListBinaryExtension = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRows_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_String___System_String_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRows_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_Int64___Int64_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRows_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_Int32___Int32_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRows_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_T_BinarySearchRow_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_T_BinarySearchFirstRow_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearch_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRowsGreater_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRowsGreaterOrEqual_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearchGreater_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearchGreaterOrEqual_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRowsLess_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__BinarySearchRowsLessOrEqual_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearchLess_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearchLessOrEqual_T_Tkey__System_Collections_Generic_List_1_T___System_Func_2_T_Tkey___Tkey_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearch_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_String___System_String_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearch_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_Int32___Int32_ = @"";

        public const string ListBinaryExtension_method_Int32_BinarySearch_T__System_Collections_Generic_List_1_T___System_Func_2_T_System_Int64___Int64_ = @"";

        public const string ListBinaryExtension_method_Int32_BinaryPosition_T__System_Collections_Generic_List_1_T___T__System_String___ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__DeepCopy_T__System_Collections_Generic_List_1_T__ = @"";

        public const string ListBinaryExtension_method_System_Collections_Generic_List_1_T__LightCopy_T__System_Collections_Generic_List_1_T__ = @"";

        public const string ListBinaryExtension_method_Int32_MultipleColumnsCompare_T__T__T__System_String___ = @"";

        public const string ListBinaryExtension___c__DisplayClass20_0 = @"";

        public const string ListBinaryExtension___c__DisplayClass21_0 = @"";

        public const string ListBinaryExtension___c__DisplayClass21_1 = @"";

        public const string ListBinaryExtension___c__DisplayClass22_0 = @"";

        public const string MyExtensions = @"";

        public const string MyExtensions_method_System_String_ToJsonString_System_Object_ = @"";

        public const string MyExtensions_method_Boolean_IsExcelDataBool_System_String__Boolean_ = @"
            <summary>
            获取excel数据的bool值
            </summary>
            <param name=""data"">单元格数据</param>
            <param name=""defaultValue"">数据为空时的默认值</param>
            <returns>数据的bool值</returns>
        ";

        public const string MyExtensions_method_Boolean_IsDecimal_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsDecimal_System_String__System_Decimal_ByRef_ = @"";

        public const string MyExtensions_method_Boolean_IsDouble_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsDouble_System_String__Double_ByRef_ = @"";

        public const string MyExtensions_method_System_String_ToFormatString_System_Decimal_ = @"
            <summary>
            格式化数字，三位加逗号
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Double_Add_Double__Double_ = @"
            <summary>
            相加
            </summary>
            <param name=""add1""></param>
            <param name=""add2""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Double_sub_Double__Double_ = @"
            <summary>
            相减
            </summary>
            <param name=""d1""></param>
            <param name=""d2""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Double_mul_Double__Double_ = @"
            <summary>
            相乖
            </summary>
            <param name=""d1""></param>
            <param name=""d2""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Double_div_Double__Double_ = @"
            <summary>
            相除
            </summary>
            <param name=""d1""></param>
            <param name=""d2""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Boolean_IsInt_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsInt_System_String__Int32_ByRef_ = @"";

        public const string MyExtensions_method_System_String_Join1_T__T____System_String_ = @"
            <summary>
            将数组转换为符号分隔的字符串
            </summary>
            <param name=""arr""></param>
            <param name=""split"">分隔符</param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_RemoveSpace_System_String_ = @"
            <summary>
            去除所有空格
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_Trim1_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsFontIco_System_String_ = @"
            <summary>
            是否是字体图标
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Boolean_IsLong_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsLong_System_String__Int64_ByRef_ = @"";

        public const string MyExtensions_method_Boolean_IsDateTime_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsDateTime_System_String__System_DateTime_ByRef_ = @"";

        public const string MyExtensions_method_Boolean_IsGuid_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsGuid_System_String__System_Guid_ByRef_ = @"";

        public const string MyExtensions_method_Boolean_IsEmptyGuid_System_Guid_ = @"
            <summary>
            判断是否为Guid.Empty
            </summary>
            <param name=""guid""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Boolean_IsUrl_System_String_ = @"";

        public const string MyExtensions_method_Boolean_IsEmail_System_String_ = @"";

        public const string MyExtensions_method_Boolean_In_Int32__Int32___ = @"
            <summary>
            判断一个整型是否包含在指定的值内
            </summary>
            <param name=""i""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_Object_DBValueOrNull_System_String_ = @"
            <summary>
            返回值或DBNull.Value
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_Decimal_ToDecimal_System_String__Int32_ = @"";

        public const string MyExtensions_method_System_Decimal_ToDecimal_System_String_ = @"";

        public const string MyExtensions_method_System_Decimal_Round_System_Decimal__Int32_ = @"";

        public const string MyExtensions_method_Double_ToDouble_System_String__Int32_ = @"";

        public const string MyExtensions_method_Double_ToDouble_System_String_ = @"";

        public const string MyExtensions_method_Double_Round_Double__Int32_ = @"";

        public const string MyExtensions_method_Int16_ToShort_System_String_ = @"";

        public const string MyExtensions_method_System_Nullable_1_System_Int32__ToIntOrNull_System_String_ = @"";

        public const string MyExtensions_method_Int32_ToInt_System_String_ = @"";

        public const string MyExtensions_method_Int32_ToInt_System_String__Int32_ = @"";

        public const string MyExtensions_method_Int64_ToLong_System_String_ = @"";

        public const string MyExtensions_method_Int16_ToInt16_System_String_ = @"";

        public const string MyExtensions_method_Int32_ToInt32_System_String_ = @"";

        public const string MyExtensions_method_Int64_ToInt64_System_String_ = @"";

        public const string MyExtensions_method_Int32_ToInt_System_Net_HttpStatusCode_ = @"";

        public const string MyExtensions_method_System_DateTime_ToDateTime_System_String_ = @"";

        public const string MyExtensions_method_System_Nullable_1_System_DateTime__ToDateTimeOrNull_System_String_ = @"";

        public const string MyExtensions_method_System_Guid_ToGuid_System_String_ = @"";

        public const string MyExtensions_method_Boolean_ToBoolean_System_String_ = @"
            <summary>
            尝试转换为Boolean类型
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_DateFormat_System_Object__System_String_ = @"
            <summary>
            尝试格式化日期字符串
            </summary>
            <param name=""date""></param>
            <param name=""format""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Boolean_IsNullOrEmpty_System_String_ = @"";

        public const string MyExtensions_method_System_String_ReplaceSql_System_String_ = @"
            <summary>
            过滤sql
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_ReplaceSelectSql_System_String_ = @"
            <summary>
            过滤查询sql
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_Replace1_System_String__System_String__System_String_ = @"
            <summary>
            过滤字符串(不区分大小写)
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_ToChineseSpell_System_String_ = @"
            <summary>
            获取汉字拼音的第一个字母
            </summary>
            <param name=""strText""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_getSpell_System_String_ = @"
            <summary>
            获取汉字拼音
            </summary>
            <param name=""cnChar""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_Interruption_System_String__Int32__System_String_ = @"
            <summary>
            截取字符串，汉字两个字节，字母一个字节
            </summary>
            <param name=""str"">字符串</param>
            <param name=""strLength"">字符串长度</param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_CutString_System_String__Int32__System_String_ = @"
            <summary>
            截取字符串，汉字两个字节，字母一个字节
            </summary>
            <param name=""str"">字符串</param>
            <param name=""strLength"">字符串长度</param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_Left_System_String__Int32_ = @"
            <summary>
            获取左边多少个字符
            </summary>
            <param name=""str""></param>
            <param name=""len""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_Right_System_String__Int32_ = @"
            <summary>
            获取右边多少个字符
            </summary>
            <param name=""str""></param>
            <param name=""len""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Int32_Size_System_String_ = @"
            <summary>
            得到实符串实际长度
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_RemoveHTML_System_String_ = @"
              <summary>   
              去除HTML标记   
              </summary>   
              <param name=""NoHTML"">包括HTML的源码   </param>   
              <returns>已经去除后的文字</returns>   
        ";

        public const string MyExtensions_method_System_String_RemoveScript_System_String_ = @"
            <summary>
            过滤js脚本
            </summary>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_RemovePageTag_System_String_ = @"
            <summary>
            替换页面标签
            </summary>
            <param name=""html""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_GetImg_System_String_ = @"
            <summary>
            取得html中的图片
            </summary>
            <param name=""HTMLStr""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String___GetImgs_System_String_ = @"
            <summary>
            取得html中的所有图片
            </summary>
            <param name=""text""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_GetRandom_Int32_ = @"
            <summary>
            产生随机字符串
            </summary>
            <returns>字符串位数</returns>
        ";

        public const string MyExtensions_method_Boolean_InPunctuation_System_String_ = @"
            <summary>
            字符串是否包含标点符号(不包括_下画线)
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_RemovePunctuationOrEmpty_System_String_ = @"
            <summary>
            去除字符串标点符号和空字符
            </summary>
            <param name=""sourceString""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_ToDateWeekString_System_DateTime_ = @"
            <summary>
            返回带星期的日期格式
            </summary>
            <param name=""date""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_ToDateTimeWeekString_System_DateTime_ = @"
            <summary>
            返回带星期的日期时间格式
            </summary>
            <param name=""date""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_HtmlEncode_System_String_ = @"
            <summary>
            HTML编码
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_UrlEncode_System_String_ = @"
            <summary>
            URL编码
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_UrlDecode_System_String_ = @"
            <summary>
            URL解码
            </summary>
            <param name=""str""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Void_SetCDataValue_System_Xml_Linq_XElement__System_String_ = @"
            <summary>
            使用CDATA的方式将value保存在指定的element中
            </summary>
            <param name=""element""></param>
            <param name=""value""></param>
        ";

        public const string MyExtensions_method_Boolean_Contains_System_String__System_String__System_StringComparison_ = @"
            <summary>
            返回一个值，该值指示指定的 System.String 对象是否出现在此字符串中。
            </summary>
            <param name=""source""></param>
            <param name=""value"">要搜寻的字符串。</param>
            <param name=""comparisonType"">指定搜索规则的枚举值之一</param>
            <returns>如果 value 参数出现在此字符串中，或者 value 为空字符串 ("""")，则为 true；否则为 false</returns>
        ";

        public const string MyExtensions_method_Boolean_Contains_System_String____System_String__System_StringComparison_ = @"
            <summary>
            通过使用默认的相等或字符比较器确定序列是否包含指定的元素。
            </summary>
            <param name=""source"">要在其中定位某个值的序列。</param>
            <param name=""value"">要在序列中定位的值。</param>
            <param name=""comparisonType"">指定搜索规则的枚举值之一</param>
            <exception cref=""T:System.ArgumentNullException"">source 为 null</exception>
            <returns>如果源序列包含具有指定值的元素，则为 true；否则为 false。</returns>
        ";

        public const string MyExtensions_method_System_String_Serialize_System_Object_ = @"
            <summary>
            序列化对象为xml字符串
            </summary>
            <param name=""obj"">要序列化的对象</param>
            <returns>xml格式字符串</returns>
        ";

        public const string MyExtensions_method_System_Guid_ToGuid_Int32_ = @"
            <summary>
            将int类型转为GUID格式
            </summary>
            <param name=""i""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_Int32_ToInt_System_Guid_ = @"
            <summary>
            将guid转换为int
            </summary>
            <param name=""guid""></param>
            <returns></returns>
        ";

        public const string MyExtensions_method_System_String_ToDateString_System_String_ = @"";

        public const string MyExtensions_method_System_String_ToDateTimeString_System_String_ = @"";

        public const string MyExtensions_method_System_String_ToDateTimeStringS_System_String_ = @"";

        public const string MyExtensions_method_System_String_ToDateString_System_DateTime_ = @"";

        public const string MyExtensions_method_System_String_ToDateTimeString_System_DateTime_ = @"";

        public const string MyExtensions_method_System_String_ToDateTimeStringS_System_DateTime_ = @"";

        public const string MyExtensions_CompareText = @"";

        public const string NullableContextAttribute = @"";

        public const string NullableContextAttribute_TypeId = @"";

        public const string Productinfo = @"";

        public const string Productinfo_Product = @"";

        public const string Productinfo_SalesDirectMarginalProfit = @"";

        public const string Productinfo_SalesMarginalProfit = @"";

        public const string Productinfo_SalesProfit = @"";

        public const string Productinfo_CostEffectivenessRatio = @"";

        public const string Productinfo_DistributorReasonableMargin = @"";

        public const string Productinfo_OnePieceSalesDirectMarginalProfit = @"";

        public const string Productinfo_OnePieceSalesMarginalProfit = @"";

        public const string Productinfo_OnePieceSalesProfit = @"";

        public const string Productinfo_OnePieceCost = @"";

        public const string Productinfo_OnePieceCostCompany = @"";

        public const string Productinfo_OnePieceCostDistributor = @"";

        public const string Productinfo_DistributorOnePieceSalesProfit = @"";

        public const string Productinfo_BreakEvenPoint = @"";

        public const string Productinfo_mOnePieceSalesDirectMarginalProfit = @"";

        public const string Productinfo_mOnePieceSalesMarginalProfit = @"";

        public const string Productinfo_mOnePieceSalesProfit = @"";

        public const string Productinfo_DistributorOnePieceSalesDirectProfit = @"";

        public const string ProductsPackage = @"产品相关信息存在产品字典里，string为产品ID，用于快速获取产品的相关属性，比如价格";

        public const string ProfitEntry = @"";

        public const string ProfitEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string ProfitEntry_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getJsonResults_System_String_ = @"";

        public const string ProfitEntry_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getProfitResults_System_String_ = @"";

        public const string ProfitEntryNew = @"";

        public const string ProfitEntryNew_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string ProfitEntryNew_method_Void_QueryConfigData__ = @"";

        public const string ProfitEntryNew_method_System_Decimal_getFormulaValue_System_String__System_String_ = @"";

        public const string ProfitEntryNew_method_Void_calcAllProfit__ = @"";

        public const string ProfitEntryNew_method_Void_mergeInvest2Product__ = @"";

        public const string ProfitEntryNew_method_System_String_GetBreakEvenPoint_System_Collections_Generic_Dictionary_2_System_String_System_Decimal___System_Collections_Generic_Dictionary_2_System_String_System_Decimal___System_Collections_Generic_List_1_System_String___System_String__System_String_ = @"";

        public const string ProfitEntryNew_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getJsonResults_System_String_ = @"";

        public const string ProfitEntryNew_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getProfitResults_System_String_ = @"";

        public const string ProfitEntryNew___c = @"";

        public const string ProfitEntryNew___c__DisplayClass45_0 = @"";

        public const string ProfitEntryXian = @"";

        public const string ProfitEntryXian_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string ProfitEntryXian_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getJsonResults_System_String_ = @"";

        public const string ProfitEntryXian_method_System_Collections_Generic_List_1_CostEngine_ProfitResults__getProfitResults_System_String_ = @"";

        public const string ProfitResults = @"";

        public const string ProfitResults_MarketOrgID = @"";

        public const string ProfitResults_RegionCD = @"";

        public const string ProfitResults_BigAreaOrgCD = @"";

        public const string ProfitResults_OfficeOrgCD = @"";

        public const string ProfitResults_StationOrgCD = @"";

        public const string ProfitResults_DTCD = @"";

        public const string ProfitResults_SalesDirectMarginalTotalProfit = @"";

        public const string ProfitResults_SalesMarginalTotalProfit = @"";

        public const string ProfitResults_SalesTotalProfit = @"";

        public const string ProfitResults_CostEffectivenessTotalRatio = @"";

        public const string ProfitResults_DistributorReasonableTotalMargin = @"";

        public const string ProfitResults_Productinfo = @"";

        public const string ProfitResults_errorMessage = @"";

        public const string Program = @"";

        public const string PromotionsCosts = @"";

        public const string PromotionsCosts_method_System_Collections_Generic_List_1_CostEngine_CostResults__getJsonTotalCostResults__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalSalesAmount4MultiProdsNoPackage__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalSalesAmount4MultiProdsNoPackage222__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalSalesAmount4MultiProdsPackage__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalCost__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalCostAmount4MultiProdsNoPackage__ = @"";

        public const string PromotionsCosts_method_Void_mergeGiftBeerAmount_System_Collections_Generic_Dictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string PromotionsCosts_method_Void_calcTotalCostAmount4SingleProd__ = @"";

        public const string PromotionsCosts_method_Void_calcTotalCostAmount4MultiProdsPackage__ = @"";

        public const string PromotionsCosts_method_Void_calcSalesAmount4Accumulated__ = @"";

        public const string PromotionsCosts_method_Void_calcSalesAmount4FixedGiftByMonth__ = @"";

        public const string PromotionsCosts_method_Void_calcSalesAmount4FixedGift__ = @"";

        public const string PromotionsCosts_method_Void_calcSalesAmount4FixedGiftOnce__ = @"";

        public const string PromotionsCosts_method_Void_calcSalesAmount4Repeat__ = @"";

        public const string PromotionsCosts_method_Void_convertStage2To1__ = @"";

        public const string PromotionsCosts_method_Void_splitAccumulatedCostToMonth__ = @"";

        public const string PromotionsCosts_method_Void_calcAccumulatedCostToMonth__ = @"";

        public const string PromotionsCosts_method_Void_splitTotalCost2Product__ = @"";

        public const string PromotionsCosts_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___cloneSalesAmount__ = @"";

        public const string PromotionsCosts___c = @"";

        public const string Sort = @"排序方式";

        public const string SP_Costs = @"";

        public const string SP_Costs_method_Void_calcPackageGiftCount__ = @"";

        public const string SP_Costs_method_Void_calcTotalCost__ = @"";

        public const string SP_Costs_method_Void_calcAgentGiftBeer__ = @"";

        public const string SP_Costs_method_Void_calcDuplicateSalesAmount4AllInvest__ = @"";

        public const string SP_Costs_method_Void_splitTotalCost2Product__ = @"";

        public const string SP_Costs_method_Void_splitTotalCost2ProductP5__ = @"";

        public const string SP_Costs_method_Void_splitGiftCost2Product__ = @"";

        public const string SP_Costs_method_Void_splitAgentGiftCost2Product__ = @"";

        public const string SP_Costs_method_Void_splitAgentGiftCost2ProductP5__ = @"";

        public const string SP_Costs_method_Void_splitTerminalGiftCost2Product__ = @"";

        public const string SP_Costs_method_Void_splitTerminalGiftCost2ProductP5__ = @"";

        public const string SP_Costs_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____cloneSalesAmount_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____ = @"";

        public const string SP_Costs_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____clonePackgeSalesAmount_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal_____System_String_ = @"";

        public const string SP_Costs_method_System_Collections_Generic_List_1_CostEngine_SP_Results__getJsonTotalCostResults__ = @"";

        public const string SP_Costs_method_Void_calcAccumulatedCostToMonth__ = @"";

        public const string SP_Costs___c = @"";

        public const string SP_Costs___c__DisplayClass42_0 = @"";

        public const string SP_Costs___c__DisplayClass55_0 = @"";

        public const string SP_Costs___c__DisplayClass55_1 = @"";

        public const string SP_Costs___c__DisplayClass55_2 = @"";

        public const string SP_Costs___c__DisplayClass55_3 = @"";

        public const string SP_Costs2 = @"";

        public const string SP_Costs2_method_Void_calcPackageGiftCount__ = @"";

        public const string SP_Costs2_method_Void_calcTotalCost__ = @"";

        public const string SP_Costs2_method_Void_calcAgentGiftBeer__ = @"";

        public const string SP_Costs2_method_Void_calcAgentGiftBeerCompany__ = @"";

        public const string SP_Costs2_method_Void_calcDuplicateSalesAmount4AllInvest__ = @"";

        public const string SP_Costs2_method_Void_splitTotalCost2Product__ = @"";

        public const string SP_Costs2_method_Void_splitTotalCost2ProductP5__ = @"";

        public const string SP_Costs2_method_Void_splitGiftCost2Product__ = @"";

        public const string SP_Costs2_method_Void_splitAgentGiftCost2Product__ = @"";

        public const string SP_Costs2_method_Void_splitAgentGiftCost2ProductP5__ = @"";

        public const string SP_Costs2_method_Void_splitTerminalGiftCost2Product__ = @"";

        public const string SP_Costs2_method_Void_splitTerminalGiftCost2ProductP5__ = @"";

        public const string SP_Costs2_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____cloneSalesAmount_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____ = @"";

        public const string SP_Costs2_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____clonePackgeSalesAmount_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal_____System_String_ = @"";

        public const string SP_Costs2_method_System_Collections_Generic_List_1_CostEngine_SP_Results__getJsonTotalCostResults__ = @"";

        public const string SP_Costs2_method_Void_calcAccumulatedCostToMonth__ = @"";

        public const string SP_Costs2___c = @"";

        public const string SP_Costs2___c__DisplayClass50_0 = @"";

        public const string SP_Costs2___c__DisplayClass50_1 = @"";

        public const string SP_Costs2___c__DisplayClass53_0 = @"";

        public const string SP_Entry = @"";

        public const string SP_Entry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string SP_Entry_method_Void_processSalesAmount__ = @"";

        public const string SP_Entry_method_Void_calcCost__ = @"";

        public const string SP_Entry_method_System_Collections_Generic_List_1_CostEngine_SP_Results__getJsonResults__ = @"";

        public const string SP_Entry___c = @"";

        public const string SP_Entry2 = @"";

        public const string SP_Entry2_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string SP_Entry2_method_Void_processSalesAmount__ = @"";

        public const string SP_Entry2_method_Void_calcCost__ = @"";

        public const string SP_Entry2_method_System_Collections_Generic_List_1_CostEngine_SP_Results__getJsonResults__ = @"";

        public const string SP_Entry2___c = @"";

        public const string SP_NormaProfitEntry = @"通用不到经销商的利润计算";

        public const string SP_NormaProfitEntry_Inxs_PriceSys = @"";

        public const string SP_NormaProfitEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"
            <summary>
            组装数据
            </summary>
            <param name=""objData""></param>
            <returns></returns>
        ";

        public const string SP_NormaProfitEntry_method_Void_calcAllProfit__ = @"
            <summary>
            计算利润
            </summary>
        ";

        public const string SP_NormaProfitEntry_method_Void_QueryConfigData__ = @"";

        public const string SP_NormaProfitEntry_method_System_Decimal_getFormulaValue_System_String__System_String__System_String_ = @"
            <summary>
            获取公式
            </summary>
            <param name=""PolicyOrgCD""></param>
            <param name=""product_id_cc""></param>
            <param name=""formula""></param>
            <returns></returns>
        ";

        public const string SP_NormaProfitEntry_method_System_Collections_Generic_List_1_CostEngine_SP_ProfitResult__getJsonResults_System_String_ = @"";

        public const string SP_NormaProfitEntry___c = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_0 = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_1 = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_2 = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_3 = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_4 = @"";

        public const string SP_NormaProfitEntry___c__DisplayClass4_5 = @"";

        public const string SP_ProfitEntry = @"";

        public const string SP_ProfitEntry_Inxs_PriceSys = @"";

        public const string SP_ProfitEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"
            <summary>
            组装数据
            </summary>
            <param name=""objData""></param>
            <returns></returns>
        ";

        public const string SP_ProfitEntry_method_Void_calcAllProfit__ = @"
            <summary>
            计算利润
            </summary>
        ";

        public const string SP_ProfitEntry_method_Void_QueryConfigData__ = @"
            <summary>
            获取配置的价格
            </summary>
        ";

        public const string SP_ProfitEntry_method_System_Decimal_getFormulaValue_System_String__System_String__System_String_ = @"";

        public const string SP_ProfitEntry_method_System_Collections_Generic_List_1_CostEngine_SP_ProfitResult__getJsonResults_System_String_ = @"";

        public const string SP_ProfitEntry___c = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_0 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_1 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_2 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_3 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_4 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_5 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_6 = @"";

        public const string SP_ProfitEntry___c__DisplayClass25_7 = @"";

        public const string SP_ProfitEntry_CRBOrganization = @"组织结构";

        public const string SP_ProfitResult = @"";

        public const string SP_ProfitResult_MarketOrgID = @"营销中心";

        public const string SP_ProfitResult_RegionCD = @"区域";

        public const string SP_ProfitResult_BigAreaOrgCD = @"销售大区";

        public const string SP_ProfitResult_OfficeOrgCD = @"业务部";

        public const string SP_ProfitResult_StationOrgCD = @"工作站";

        public const string SP_ProfitResult_DTCD = @"最小业务单元";

        public const string SP_ProfitResult_OrgCD = @"组织编码";

        public const string SP_ProfitResult_PlanID = @"方案ID";

        public const string SP_ProfitResult_PolicyCode = @"政策编码";

        public const string SP_ProfitResult_TemplateCD = @"销售政策模板编码";

        public const string SP_ProfitResult_ProductCD = @"产品编码";

        public const string SP_ProfitResult_CharacterCD = @"特征码";

        public const string SP_ProfitResult_SalesAmount = @"销量";

        public const string SP_ProfitResult_SalesAmountKL = @"销量千升";

        public const string SP_ProfitResult_Income = @"收入";

        public const string SP_ProfitResult_TaxAdditional = @"税金及附加";

        public const string SP_ProfitResult_CostChanged = @"可变成本";

        public const string SP_ProfitResult_InvestCost = @"政策投入费用";

        public const string SP_ProfitResult_AmountCost = @"随量费用:折扣+瓶盖";

        public const string SP_ProfitResult_SalesDirectMarginalProfit = @"销售直接边际";

        public const string SP_ProfitResult_SalesMarginalProfit = @"销售边际利润";

        public const string SP_ProfitResult_GongTan = @"公摊";

        public const string SP_ProfitResult_FixedFee = @"固定";

        public const string SP_ProfitResult_SalesProfit = @"销售利润";

        public const string SP_ProfitResult_IfRemoved = @"是否剔除";

        public const string SP_Results = @"";

        public const string SP_Results_CostType = @"";

        public const string SP_Results_AgentID = @"";

        public const string SP_Results_TerminalID = @"";

        public const string SP_Results_PackageID = @"";

        public const string SP_Results_ItemID = @"";

        public const string SP_Results_ProductName = @"";

        public const string SP_Results_CostbyMonth = @"";

        public const string SP_Results_CostbyMonthP5 = @"";

        public const string SP_Results_GiftID = @"";

        public const string SP_SubsidyStage2 = @"";

        public const string SP_SubsidyStage2_IsSplited = @"";

        public const string SP_SubsidyStage2_listDLbyMonthStandard = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetCompanyCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetGiftMoneyCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetSPGiftBeerCost_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetSPGiftThingCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetSPGiftBeerCompanyCost_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetSPGiftThingCompanyCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Decimal_GetSPCompanyCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SP_SubsidyStage2_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftBeerAmount_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftBeerAmountCompany_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftBeerLastCompanyRate_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftThingAmount_System_Decimal_ = @"";

        public const string SP_SubsidyStage2_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftThingAmountCompany_System_Decimal_ = @"";

        public const string SPDelayedDiscountUtils = @"";

        public const string SPDelayedDiscountUtils_Inxs_IMDelayedDiscount = @"";

        public const string SPDelayedDiscountUtils_method_Void_ComplatePriceSystem_CostEngine_Data_Domain_M_PriceSys__System_DateTime__OrgSearchModel_ = @"";

        public const string SPDelayedDiscountUtils_method_Boolean_NotLoadBaseData__ = @"";

        public const string SPDelayedDiscountUtils___c__DisplayClass9_0 = @"";

        public const string SPDelayedDiscountUtils_OrgSearchModel = @"组织维度筛选实体";

        public const string SPDelayedDiscountUtils_OrgSearchModel_MarketOrgCD = @"营销中心";

        public const string SPDelayedDiscountUtils_OrgSearchModel_BigAreaOrgCD = @"销售大区";

        public const string SPDelayedDiscountUtils_OrgSearchModel_OfficeOrgCD = @"业务部";

        public const string SPDelayedDiscountUtils_OrgSearchModel_StationOrgCD = @"工作站";

        public const string SPDelayedDiscountUtils_OrgSearchModel_DTCD = @"经销商";

        public const string SPDelayedDiscountUtils_OrgSearchModel_ProductCD = @"产品编码";

        public const string SPDelayedDiscountUtils_OrgSearchModel_CharacterCD = @"特征码";

        public const string Stage = @"";

        public const string Stage_StageInt = @"";

        public const string Stage_SubsidyRate = @"";

        public const string Stage_SubsidyBaseNum = @"";

        public const string Stage_SubsidyGiftNum = @"";

        public const string Stage_SubsidyRateCompany = @"";

        public const string Stage_SubsidyCompanyType = @"";

        public const string Stage2 = @"";

        public const string Stage2_StageInt = @"";

        public const string Stage2_GiftMoney = @"";

        public const string Stage2_SubsidyRateCompany = @"";

        public const string Stage2_SubsidyBaseNum = @"";

        public const string Stage2_SubsidyGiftNum = @"";

        public const string SubsidyStage = @"";

        public const string SubsidyStage_IsSplited = @"";

        public const string SubsidyStage_listDLbyMonthStandard = @"";

        public const string SubsidyStage_method_System_Decimal_GetCost_System_Decimal__Int32_ = @"";

        public const string SubsidyStage_method_System_Decimal_GetCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SubsidyStage_method_System_Decimal_GetSPCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SubsidyStage_method_System_Decimal_GetSPGiftCost_System_Decimal__System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Decimal_GetSPGiftCompanyCost_System_Decimal__System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Decimal_GetCompanyCost_System_Decimal__Int32_ = @"";

        public const string SubsidyStage_method_System_Decimal_GetCompanyCost_System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Decimal_GetSPCompanyCost_System_Decimal__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string SubsidyStage_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftAmount_System_Decimal__Int32_ = @"";

        public const string SubsidyStage_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftAmount_System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftAmountCompany_System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftThingAmount_System_Decimal_ = @"";

        public const string SubsidyStage_method_System_Collections_Generic_Dictionary_2_System_String_System_Decimal__GetGiftThingAmountCompany_System_Decimal_ = @"";

        public const string SubsidyStage___c = @"";

        public const string TP_CostEntry = @"";

        public const string TP_CostEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string TP_CostEntry_method_System_String_calcCost__ = @"";

        public const string TP_CostEntry_method_System_Collections_Generic_List_1_CostEngine_CostResults__getJsonResults__ = @"";

        public const string TP_CostEntry___c = @"";

        public const string TP_Costs = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_CostEngine_CostResults__getJsonTotalCostResults__ = @"";

        public const string TP_Costs_method_Void_calcTotalAmount4MultiProdsNoPackage__ = @"";

        public const string TP_Costs_method_Void_calcTotalAmount4MultiProdsNoPackageSingleProdControl__ = @"";

        public const string TP_Costs_method_Void_calcTotalAmount4MultiProdsNoPackageAddRemain__ = @"";

        public const string TP_Costs_method_Void_calcTotalSalesAmount4MultiProdsNoPackage222__ = @"";

        public const string TP_Costs_method_Void_calcTotalSalesAmount4MultiProdsPackage__ = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_System_Decimal__calcPackageCount_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_System_Decimal__calcPackageCountNonRoutine_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_System_Decimal__calcPackageCountNonRoutineStages_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_System_Decimal__calcPackageCountNonRoutineCycle_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_System_Collections_Generic_List_1_System_Decimal__calcPackageCountNonRoutineFixed_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_Int32_getCycleTimes_Int32_ = @"";

        public const string TP_Costs_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___calcTotalDLSplit_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____System_Decimal____CostEngine_ProductsPackage__System_String_ = @"";

        public const string TP_Costs_method_Void_calcTotalCost__ = @"";

        public const string TP_Costs_method_Void_mergeGiftBeerAmount_System_Collections_Generic_Dictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___ = @"";

        public const string TP_Costs_method_Void_calcTotalCostAmount4SingleProd__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4Accumulated__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4FixedGiftByMonth__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4FixedGiftByMonthNonRoutine__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4FixedGift__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4FixedGiftOnce__ = @"";

        public const string TP_Costs_method_Void_calcSalesAmount4Repeat__ = @"";

        public const string TP_Costs_method_Void_convertStage2To1__ = @"";

        public const string TP_Costs_method_Void_splitAccumulatedCostToMonth__ = @"";

        public const string TP_Costs_method_Void_calcAccumulatedCostToMonth__ = @"";

        public const string TP_Costs_method_Void_splitTotalCost2Product__ = @"";

        public const string TP_Costs_method_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal___cloneSalesAmount__ = @"";

        public const string TP_Costs_method_Void_ReplaceAdjustSaleAmount_CostEngine_ProductsPackage__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal_____ = @"";

        public const string TP_Costs_method_Void_ReplaceAdjustOriginalSaleAmount_CostEngine_ProductsPackage__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal_____ = @"";

        public const string TP_Costs_method_Void_ReplaceAdjustTotalSaleAmount_CostEngine_ProductsPackage__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal_____ = @"";

        public const string TP_Costs_method_Void_ReplaceAdjustSaleAmount_CostEngine_ProductsPackage__System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Generic_List_1_System_Decimal____System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal_____ = @"";

        public const string TP_Costs___c = @"";

        public const string TP_Costs___c__DisplayClass36_0 = @"";

        public const string TP_Costs___c__DisplayClass36_1 = @"";

        public const string TP_Costs___c__DisplayClass37_0 = @"";

        public const string TP_Costs___c__DisplayClass39_0 = @"";

        public const string TP_Costs___c__DisplayClass39_1 = @"";

        public const string TP_Costs___c__DisplayClass39_2 = @"";

        public const string TP_ProfitEntry = @"";

        public const string TP_ProfitEntry_method_System_String_ParseJsonParameter_Newtonsoft_Json_Linq_JObject___ = @"";

        public const string TP_ProfitEntry_method_Void_QueryConfigData__ = @"
            <summary>
            配置数据
            </summary>
            <exception cref=""T:System.Exception""></exception>
        ";

        public const string TP_ProfitEntry_method_Void_calcAllProfit__ = @"";

        public const string TP_ProfitEntry_method_Void_processGiftBeer__ = @"";

        public const string TP_ProfitEntry_method_Void_sumCompanyTotalProfit__ = @"";

        public const string TP_ProfitEntry_method_System_Decimal_getFormulaValue_System_String__System_String_ = @"";

        public const string TP_ProfitEntry_method_System_Collections_Generic_List_1_CostEngine_TP_ProfitResult__getJsonResults_System_String_ = @"";

        public const string TP_ProfitEntry_method_System_String_GetBreakEvenPoint_System_Collections_Generic_Dictionary_2_System_String_System_Decimal___System_Collections_Concurrent_ConcurrentDictionary_2_System_String_System_Decimal___System_Collections_Generic_List_1_System_String___System_String__System_Decimal__System_Decimal_ = @"";

        public const string TP_ProfitEntry_method_System_Collections_Generic_List_1_System_String__getFormulaValueStr_System_String__System_String_ = @"";

        public const string TP_ProfitEntry_method_System_Decimal_getPriceFormulaValue_CostEngine_Data_Domain_M_PriceSys__System_String_ = @"";

        public const string TP_ProfitEntry___c = @"";

        public const string TP_ProfitEntry___c__DisplayClass48_0 = @"";

        public const string TP_ProfitEntry___c__DisplayClass49_0 = @"";

        public const string TP_ProfitEntry_CRBOrganization = @"组织结构";

        public const string TP_ProfitResult = @"";

        public const string TP_ProfitResult_MarketOrgID = @"";

        public const string TP_ProfitResult_RegionCD = @"";

        public const string TP_ProfitResult_BigAreaOrgCD = @"";

        public const string TP_ProfitResult_OfficeOrgCD = @"";

        public const string TP_ProfitResult_StationOrgCD = @"";

        public const string TP_ProfitResult_DTCD = @"";

        public const string TP_ProfitResult_ProductCD = @"";

        public const string TP_ProfitResult_CharacterCD = @"";

        public const string TP_ProfitResult_SalesAmount = @"";

        public const string TP_ProfitResult_InvoicePrice = @"";

        public const string TP_ProfitResult_DirectMarginFormula = @"";

        public const string TP_ProfitResult_DirectMargin = @"";

        public const string TP_ProfitResult_SingleAmountDirectMargin = @"";

        public const string TP_ProfitResult_SingleDirectMargin = @"";

        public const string TP_ProfitResult_SalesMarginProfit = @"";

        public const string TP_ProfitResult_SalesProfit = @"";

        public const string TP_ProfitResult_SingleAmountCost = @"";

        public const string TP_ProfitResult_SingleCost = @"";

        public const string TP_ProfitResult_CostBenifitRatio = @"";

        public const string TP_ProfitResult_BEP = @"";

        public const string TP_ProfitResult_Agent1stProfit = @"";

        public const string TP_ProfitResult_Agent2ndProfit = @"";

        public const string TP_ProfitResult_Agent1stSingleCost = @"";

        public const string TP_ProfitResult_Agent1stSingleProfit = @"";

        public const string TP_ProfitResult_Agent2ndSingleCost = @"";

        public const string TP_ProfitResult_Agent2ndSingleProfit = @"";

        public const string TP_ProfitResult_TerminalProfitFloor = @"";

        public const string TP_ProfitResult_TerminalProfitCAP = @"";

        public const string TP_ProfitResult_TerminalProfitForcast = @"";

        public const string TP_ProfitResult_TerminalSingleCost = @"";

        public const string TP_ProfitResult_Income = @"";

        public const string TP_ProfitResult_TPCalcTax = @"";

        public const string TP_ProfitResult_SingleDirectMarginal = @"";

        public const string TP_ProfitResult_KLDirectMarginal = @"";

        public const string TP_ProfitResult_SingleSalesMarginal = @"";

        public const string TP_ProfitResult_KLSalesMarginal = @"";

        public const string TP_ProfitResult_SingleSalesProfit = @"";

        public const string TP_ProfitResult_KLSalesProfit = @"";

        public const string TP_ProfitResult_BearAmount = @"";

        public const string TP_ProfitResult_BearAmountKL = @"";

        public const string TP_ProfitResult_GiftAmount = @"";

        public const string TP_ProfitResult_SingleDirectMarginFormulaDesc = @"";

        public const string TP_ProfitResult_SingleDirectMarginFormulaValue = @"";

        public const string TP_ProfitResult_DirectMarginDesc = @"";

        public const string TP_ProfitResult_DirectMarginValue = @"";

    }
}
