//-----------------------------------------------------------------------
// 此文件由TryCostEngine自动生成
// 对该文件的任何更改都将在生成时被覆盖
// <auto-generated />
//-----------------------------------------------------------------------

namespace TryCostEngine.MAUI.Models
{
    public static partial class Snippets
    {
    }
}
